# Generated by Django 6.0.6 on 2026-06-30 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('equipment', '0002_certificado_atualizado_por_certificado_criado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlocacaoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de fim')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.equipamento', verbose_name='Equipamento')),
            ],
            options={
                'verbose_name': 'Alocação de equipamento',
                'verbose_name_plural': 'Alocações de equipamentos',
            },
        ),
        migrations.CreateModel(
            name='AlocacaoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de fim')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Alocação de funcionário',
                'verbose_name_plural': 'Alocações de funcionários',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome')),
                ('nif', models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='NIF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim_prevista', models.DateField(blank=True, null=True, verbose_name='Data de fim prevista')),
                ('estado', models.CharField(choices=[('planeada', 'Planeada'), ('em_curso', 'Em curso'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='planeada', max_length=12, verbose_name='Estado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='projects.cliente', verbose_name='Cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('equipamentos', models.ManyToManyField(related_name='obras', through='projects.AlocacaoEquipamento', to='equipment.equipamento', verbose_name='Equipamentos alocados')),
                ('funcionarios', models.ManyToManyField(related_name='obras', through='projects.AlocacaoFuncionario', to='employees.funcionario', verbose_name='Funcionários alocados')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AddField(
            model_name='alocacaofuncionario',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.obra', verbose_name='Obra'),
        ),
        migrations.AddField(
            model_name='alocacaoequipamento',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.obra', verbose_name='Obra'),
        ),
        migrations.AlterUniqueTogether(
            name='alocacaofuncionario',
            unique_together={('obra', 'funcionario')},
        ),
        migrations.AlterUniqueTogether(
            name='alocacaoequipamento',
            unique_together={('obra', 'equipamento')},
        ),
    ]
