# Generated by Django 6.0.6 on 2026-06-30 12:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alocacaoequipamento',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Alocação de equipamento', 'verbose_name_plural': 'Alocações de equipamentos'},
        ),
        migrations.AlterModelOptions(
            name='alocacaofuncionario',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Alocação de funcionário', 'verbose_name_plural': 'Alocações de funcionários'},
        ),
        migrations.AddField(
            model_name='alocacaoequipamento',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='alocacaoequipamento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alocacaofuncionario',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='alocacaofuncionario',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
    ]
