# Generated by Django 6.0.6 on 2026-07-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_alocacaoequipamento_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='equipamentos',
        ),
        migrations.DeleteModel(
            name='AlocacaoEquipamento',
        ),
    ]
