# Generated by Django 6.0.6 on 2026-08-12 09:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_obra_equipamentos_delete_alocacaoequipamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='Ano')),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Mês')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor (€)')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('estado', models.CharField(choices=[('por_faturar', 'Por faturar'), ('faturado', 'Faturado')], default='por_faturar', max_length=12, verbose_name='Estado')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autos', to='projects.obra', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Auto de obra',
                'verbose_name_plural': 'Autos de obras',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('obra', 'ano', 'mes')},
            },
        ),
    ]
