# Generated by Django 6.0.6 on 2026-07-14 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_despesafuncionario_atualizado_em_and_more'),
        ('equipment', '0003_certificado_atualizado_em_certificado_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='employees.funcionario', verbose_name='Responsável'),
        ),
    ]
