# Generated by Django 5.1.15 on 2026-06-26 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('marca', models.CharField(max_length=60, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=60, verbose_name='Modelo')),
                ('ano', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Viatura',
                'verbose_name_plural': 'Viaturas',
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='SeguroViatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_validade', models.DateField(db_index=True, verbose_name='Data de validade')),
                ('seguradora', models.CharField(max_length=80, verbose_name='Seguradora')),
                ('apolice', models.CharField(max_length=60, verbose_name='Nº de apólice')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguros', to='fleet.viatura', verbose_name='Viatura')),
            ],
            options={
                'verbose_name': 'Seguro de viatura',
                'verbose_name_plural': 'Seguros de viaturas',
                'ordering': ['data_validade'],
            },
        ),
        migrations.CreateModel(
            name='Inspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_validade', models.DateField(db_index=True, verbose_name='Data de validade')),
                ('data_inspecao', models.DateField(verbose_name='Data da inspeção')),
                ('resultado', models.CharField(choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='aprovado', max_length=10, verbose_name='Resultado')),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecoes', to='fleet.viatura', verbose_name='Viatura')),
            ],
            options={
                'verbose_name': 'Inspeção',
                'verbose_name_plural': 'Inspeções',
                'ordering': ['data_validade'],
            },
        ),
        migrations.CreateModel(
            name='DespesaViatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (€)')),
                ('data', models.DateField(verbose_name='Data')),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='fleet.viatura', verbose_name='Viatura')),
            ],
            options={
                'verbose_name': 'Despesa de viatura',
                'verbose_name_plural': 'Despesas de viaturas',
                'ordering': ['-data'],
            },
        ),
    ]
