# Generated by Django 6.0.6 on 2026-08-12 09:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_despesafuncionario_atualizado_em_and_more'),
        ('fleet', '0004_despesaviatura_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguroviatura',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor (€)'),
        ),
        migrations.AddField(
            model_name='viatura',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaturas', to='employees.funcionario', verbose_name='Responsável'),
        ),
    ]
