# Generated by Django 6.0.6 on 2026-06-30 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_validade', models.DateField(db_index=True, verbose_name='Data de validade')),
                ('aptidao', models.CharField(choices=[('apto', 'Apto'), ('apto_restricoes', 'Apto com restrições'), ('nao_apto', 'Não apto')], max_length=20, verbose_name='Aptidão')),
                ('data_exame', models.DateField(verbose_name='Data do exame')),
                ('medico', models.CharField(blank=True, max_length=160, verbose_name='Médico / entidade')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ficha_medica', to='employees.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Ficha médica',
                'verbose_name_plural': 'Fichas médicas',
                'ordering': ['data_validade'],
            },
        ),
    ]
