# Generated by Django 6.0.6 on 2026-07-14 17:46

import config.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichamedica',
            name='medico',
            field=config.encryption.EncryptedTextField(blank=True, verbose_name='Médico / entidade'),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='observacoes',
            field=config.encryption.EncryptedTextField(blank=True, verbose_name='Observações'),
        ),
    ]
